import moment from 'moment';

export default [{
  car: 1,
  firstName: 'Bill',
  lastName: 'Gates',
  age: 18,
  status: 'open',
  estimatedDate: moment().subtract(3, 'days').toISOString(),
  returnDate: null,
  dateFrom: moment().subtract(5, 'days').toISOString(),
  pricePerDay: 50,
},
{
  car: 2,
  firstName: 'Ivan',
  lastName: 'Ivanov',
  age: 30,
  status: 'open',
  estimatedDate: moment().subtract(1, 'days').toISOString(),
  returnDate: null,
  dateFrom: moment().subtract(5, 'days').toISOString(),
  pricePerDay: 50,
},
{
  car: 3,
  firstName: 'Petar',
  lastName: 'Gerogiev',
  age: 25,
  status: 'open',
  estimatedDate: moment().add(1, 'days').toISOString(),
  returnDate: null,
  dateFrom: moment().subtract(5, 'days').toISOString(),
  pricePerDay: 50,
},
{
  car: 4,
  firstName: 'Petko',
  lastName: 'Petkov',
  age: 26,
  status: 'open',
  estimatedDate: moment().add(5, 'days').toISOString(),
  returnDate: null,
  dateFrom: moment().subtract(5, 'days').toISOString(),
  pricePerDay: 50,
}];